
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {Toaster} from "sonner"
import ThemeClient from "@/components/themeprovider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemon",
  description: "Generated by reem ebrahim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeClient>
       <Toaster theme="dark" position="bottom-center"/>
        {children}
      </ThemeClient>
        </body>
    </html>
  );
}
